baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My Blog'

[taxonomies]
  tag = 'tags'

[menus]
  [[menus.main]]
    name = 'about'
    pageRef = '/about'
    weight = 10

  [[menus.main]]
    name = 'tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
